-- MySQL Script generated by MySQL Workbench
-- Fri Feb 13 05:08:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbtiendas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbtiendas` ;

-- -----------------------------------------------------
-- Schema dbtiendas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbtiendas` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `dbtiendas` ;

-- -----------------------------------------------------
-- Table `dbtiendas`.`cargo_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`cargo_empleado` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`cargo_empleado` (
  `id_cargo` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  CONSTRAINT `cargo_empleado_cargos_FK`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `dbtiendas`.`cargos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cargo_empleado_empleado_FK`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `dbtiendas`.`empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `cargo_empleado_cargos_FK` ON `dbtiendas`.`cargo_empleado` (`id_cargo` ASC) VISIBLE;

CREATE INDEX `cargo_empleado_empleado_FK` ON `dbtiendas`.`cargo_empleado` (`id_empleado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`cargos` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`cargos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`categorias` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`comisiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`comisiones` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`comisiones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_locale` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `porcentaje` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `loca`
    FOREIGN KEY (`id_locale`)
    REFERENCES `dbtiendas`.`locales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `locale_idx` ON `dbtiendas`.`comisiones` (`id_locale` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`empleado` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`empleado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(100) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`empleado_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`empleado_user` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`empleado_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_empleado` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `empleado_user_empleado_FK`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `dbtiendas`.`empleado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `empleado_user_users_FK`
    FOREIGN KEY (`id_user`)
    REFERENCES `dbtiendas`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `empleado_user_empleado_FK` ON `dbtiendas`.`empleado_user` (`id_empleado` ASC) VISIBLE;

CREATE INDEX `empleado_user_users_FK` ON `dbtiendas`.`empleado_user` (`id_user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`factura_venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`factura_venta` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`factura_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nrofactura` VARCHAR(100) NULL DEFAULT NULL,
  `id_venta_cabezera` INT NOT NULL,
  `id_locale` INT NULL DEFAULT NULL,
  `id_tasabcv` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `factura_venta_locales_FK`
    FOREIGN KEY (`id_locale`)
    REFERENCES `dbtiendas`.`locales` (`id`),
  CONSTRAINT `factura_venta_tasabcv_FK`
    FOREIGN KEY (`id_tasabcv`)
    REFERENCES `dbtiendas`.`tasabcv` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `factura_venta_venta_cabezera_FK`
    FOREIGN KEY (`id_venta_cabezera`)
    REFERENCES `dbtiendas`.`venta_cabezera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `factura_venta_venta_cabezera_FK` ON `dbtiendas`.`factura_venta` (`id_venta_cabezera` ASC) VISIBLE;

CREATE INDEX `factura_venta_locales_FK` ON `dbtiendas`.`factura_venta` (`id_locale` ASC) VISIBLE;

CREATE INDEX `factura_venta_tasabcv_FK` ON `dbtiendas`.`factura_venta` (`id_tasabcv` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`forma_pago_factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`forma_pago_factura` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`forma_pago_factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_factura_venta` INT NULL DEFAULT NULL,
  `id_forma_pago` INT NOT NULL,
  `monto` DECIMAL(10,0) NOT NULL,
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `forma_pago_factura_factura_venta_FK`
    FOREIGN KEY (`id_factura_venta`)
    REFERENCES `dbtiendas`.`factura_venta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `forma_pago_factura_formapagos_FK`
    FOREIGN KEY (`id_forma_pago`)
    REFERENCES `dbtiendas`.`formapagos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `forma_pago_factura_factura_venta_FK` ON `dbtiendas`.`forma_pago_factura` (`id_factura_venta` ASC) VISIBLE;

CREATE INDEX `forma_pago_factura_formapagos_FK` ON `dbtiendas`.`forma_pago_factura` (`id_forma_pago` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`formapagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`formapagos` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`formapagos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`locale_empledos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`locale_empledos` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`locale_empledos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NULL DEFAULT NULL,
  `id_locale` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `locale_empledos_empleado_FK`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `dbtiendas`.`empleado` (`id`),
  CONSTRAINT `locale_empledos_locales_FK`
    FOREIGN KEY (`id_locale`)
    REFERENCES `dbtiendas`.`locales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `locale_empledos_empleado_FK` ON `dbtiendas`.`locale_empledos` (`id_empleado` ASC) VISIBLE;

CREATE INDEX `locale_empledos_locales_FK` ON `dbtiendas`.`locale_empledos` (`id_locale` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`locale_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`locale_user` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`locale_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_locale` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `locale_user_locales_FK`
    FOREIGN KEY (`id_locale`)
    REFERENCES `dbtiendas`.`locales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `locale_user_users_FK`
    FOREIGN KEY (`id_user`)
    REFERENCES `dbtiendas`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `locale_user_users_FK` ON `dbtiendas`.`locale_user` (`id_user` ASC) VISIBLE;

CREATE INDEX `locale_user_locales_FK` ON `dbtiendas`.`locale_user` (`id_locale` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`locales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`locales` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`locales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `rif` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(200) NOT NULL,
  `estado` VARCHAR(100) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'define cada uno de los locales del sistema o tiendas';

CREATE UNIQUE INDEX `locales_unique` ON `dbtiendas`.`locales` (`name` ASC) VISIBLE;

CREATE UNIQUE INDEX `locales_unique_1` ON `dbtiendas`.`locales` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`productos` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `id_locale` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `precio` DECIMAL(10,0) NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio2` DECIMAL(10,0) NULL DEFAULT NULL,
  `marca` VARCHAR(100) NULL DEFAULT NULL,
  `model` VARCHAR(100) NULL DEFAULT NULL,
  `reposicion` INT NULL DEFAULT NULL,
  `_id_ubicacion` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos_categorias_FK`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `dbtiendas`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `productos_locales_FK`
    FOREIGN KEY (`id_locale`)
    REFERENCES `dbtiendas`.`locales` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `productos_ubicaciones_FK`
    FOREIGN KEY (`_id_ubicacion`)
    REFERENCES `dbtiendas`.`ubicaciones` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `productos_name_IDX` USING BTREE ON `dbtiendas`.`productos` (`name`, `marca`) VISIBLE;

CREATE INDEX `productos_categorias_FK` ON `dbtiendas`.`productos` (`id_categoria` ASC) VISIBLE;

CREATE INDEX `productos_locales_FK` ON `dbtiendas`.`productos` (`id_locale` ASC) VISIBLE;

CREATE INDEX `productos_ubicaciones_FK` ON `dbtiendas`.`productos` (`_id_ubicacion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`promotores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`promotores` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`promotores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`role_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`role_user` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`role_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_role` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `idrole`
    FOREIGN KEY (`id_role`)
    REFERENCES `dbtiendas`.`roles` (`id`),
  CONSTRAINT `iduser`
    FOREIGN KEY (`id_user`)
    REFERENCES `dbtiendas`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `idrole_idx` ON `dbtiendas`.`role_user` (`id_role` ASC) VISIBLE;

CREATE INDEX `iduser_idx` ON `dbtiendas`.`role_user` (`id_user` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`roles` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `update` VARCHAR(1) NOT NULL DEFAULT 'N',
  `create` VARCHAR(1) NOT NULL DEFAULT 'N',
  `read` VARCHAR(1) NOT NULL DEFAULT 'N',
  `delete` VARCHAR(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `name_UNIQUE` ON `dbtiendas`.`roles` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`tasabcv`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`tasabcv` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`tasabcv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL DEFAULT NULL,
  `monto` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`tecnicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`tecnicos` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`tecnicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`ubicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`ubicaciones` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`ubicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_locales` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `dbtiendas`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`users` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `name_UNIQUE` ON `dbtiendas`.`users` (`name` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `dbtiendas`.`users` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`venta_cabezera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`venta_cabezera` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`venta_cabezera` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_promotor` INT NULL DEFAULT NULL,
  `id_tecnico` INT NULL DEFAULT NULL,
  `locale_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `venta_cabezera_roles_FK`
    FOREIGN KEY (`locale_id`)
    REFERENCES `dbtiendas`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `venta_cabezera_roles_FK` ON `dbtiendas`.`venta_cabezera` (`locale_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`venta_footer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`venta_footer` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`venta_footer` (
  `iva` DECIMAL(10,0) NULL DEFAULT NULL,
  `descuento` DECIMAL(10,0) NULL DEFAULT NULL,
  `total` DECIMAL(10,0) NULL DEFAULT NULL,
  `venta_cabezera_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `subtotal` DECIMAL(10,0) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `venta_footer_venta_cabezera_FK`
    FOREIGN KEY (`venta_cabezera_id`)
    REFERENCES `dbtiendas`.`venta_cabezera` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `venta_footer_venta_cabezera_FK` ON `dbtiendas`.`venta_footer` (`venta_cabezera_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`venta_promotores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`venta_promotores` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`venta_promotores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_promotor` INT NULL DEFAULT NULL,
  `monto` DECIMAL(10,0) NOT NULL,
  `fecha_venta` DATE NULL DEFAULT NULL,
  `fecha_pago` DATE NULL DEFAULT NULL,
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `pagado` VARCHAR(100) NULL DEFAULT '"N"',
  `id_factura_venta` INT NOT NULL,
  `id_locale` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `venta_promotores_factura_venta_FK`
    FOREIGN KEY (`id_factura_venta`)
    REFERENCES `dbtiendas`.`factura_venta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `venta_promotores_promotores_FK`
    FOREIGN KEY (`id_promotor`)
    REFERENCES `dbtiendas`.`promotores` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `venta_promotores_promotores_FK` ON `dbtiendas`.`venta_promotores` (`id_promotor` ASC) VISIBLE;

CREATE INDEX `venta_promotores_factura_venta_FK` ON `dbtiendas`.`venta_promotores` (`id_factura_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`venta_tecnicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`venta_tecnicos` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`venta_tecnicos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_locale` INT NOT NULL,
  `id_tecnico` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL,
  `id_factura_venta` INT NOT NULL,
  `fecha_venta` DATE NULL DEFAULT NULL,
  `fecha_pago` DATE NULL DEFAULT NULL,
  `referencia` VARCHAR(100) NULL DEFAULT NULL,
  `venta_tecnicoscol` VARCHAR(45) NULL DEFAULT NULL,
  `pagado` VARCHAR(45) NULL DEFAULT '"N''',
  PRIMARY KEY (`id`),
  CONSTRAINT `factura`
    FOREIGN KEY (`id_factura_venta`)
    REFERENCES `dbtiendas`.`factura_venta` (`id`),
  CONSTRAINT `locale`
    FOREIGN KEY (`id_locale`)
    REFERENCES `dbtiendas`.`locales` (`id`),
  CONSTRAINT `tecnico`
    FOREIGN KEY (`id_tecnico`)
    REFERENCES `dbtiendas`.`tecnicos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `locale_idx` ON `dbtiendas`.`venta_tecnicos` (`id_locale` ASC) VISIBLE;

CREATE INDEX `tecnico_idx` ON `dbtiendas`.`venta_tecnicos` (`id_tecnico` ASC) VISIBLE;

CREATE INDEX `factura_idx` ON `dbtiendas`.`venta_tecnicos` (`id_factura_venta` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `dbtiendas`.`ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbtiendas`.`ventas` ;

CREATE TABLE IF NOT EXISTS `dbtiendas`.`ventas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_producto` INT NULL DEFAULT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio` DECIMAL(10,0) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `venta_cabezera_id` INT NOT NULL,
  `precio_promotor` DECIMAL(10,0) NULL DEFAULT NULL,
  `total` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `ventas_productos_FK`
    FOREIGN KEY (`id_producto`)
    REFERENCES `dbtiendas`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ventas_productos_FK` ON `dbtiendas`.`ventas` (`id_producto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
