<?php

return [
     'admin' => ['admin'],
            'roles.index' => ['admin'],
            'roles.create' => ['admin'],
            'roles.edit' => ['admin'],
            'roles.update' => ['admin'],
            'roles.destroy' => ['admin'],
            'roles.assign' => ['admin'],
            'roles.assignRole' => ['admin'],
            'roles.revokeRole' => ['admin'],
            'tienda_cargo.index' => ['admin'],
            'tienda_cargo.create' => ['admin'],
            'tienda_cargo.edit' => ['admin'],
            'tienda_cargo.update' => ['admin'],
            'tienda_cargo.destroy' => ['admin'],
            'users.index' => ['admin'],
            'users.create' => ['admin'],
            'users.edit' => ['admin'],
            'users.update' => ['admin'],
            'users.destroy' => ['admin'],
            'users.assign' => ['admin'],
            'users.assignRole' => ['admin'],
            'users.revokeRole' => ['admin'],
            'locales.index' => ['admin'],
            'locales.create' => ['admin'],
            'locales.edit' => ['admin'],
            'locales.update' => ['admin'],
            'locales.destroy' => ['admin'],
            'empleados.index'=>['admin'],
            'empleados.create'=>['admin'],
            'empleados.store'=>['admin'],
            'empleados.edit'=>['admin'],
            'empleados.update'=>['admin'],
            'empleados.destroy'=>['admin'],
            'cargos.index'=>['admin'],
            'cargos.create'=>['admin'],
            'cargos.store'=>['admin'],
            'cargos.edit'=>['admin'],
            'cargos.update'=>['admin'],
            'cargos.destroy'=>['admin'],
            'cargo.asignacargo'=>['admin'],
            'cargoEmpleados.index'=>['admin'],
            'cargoEmpleados.create'=>['admin'],
            'cargoEmpleados.store'=>['admin'],
            'cargoEmpleados.edit'=>['admin'],
            'cargoEmpleados.update'=>['admin'],
            'cargoEmpleados.destroy'=>['admin'],
            'empleadoUsers.index'=>['admin'],
            'empleadoUsers.create'=>['admin'],
            'empleadoUsers.store'=>['admin'],
            'empleadoUsers.edit'=>['admin'],
            'empleadoUsers.update'=>['admin'],
            'empleadoUsers.destroy'=>['admin'],
            'localeUsers.index'=>['admin'],
            'localeUsers.create'=>['admin'],
            'localeUsers.store'=>['admin'],
            'localeUsers.edit'=>['admin'],
            'localeUsers.update'=>['admin'],
            'localeUsers.destroy'=>['admin'],
            'categorias.index'=>['admin'],
            'categorias.create'=>['admin'],
            'categorias.store'=>['admin'],
            'categorias.edit'=>['admin'],
            'categorias.update'=>['admin'],
            'categorias.destroy'=>['admin'],
            'promotores.index'=>['admin'],
            'promotores.create'=>['admin'],
            'promotores.store'=>['admin'],
            'promotores.edit'=>['admin'],
            'promotores.update'=>['admin'],
            'promotores.destroy'=>['admin'],
            'tecnicos.index'=>['admin'],
            'tecnicos.create'=>['admin'],
            'tecnicos.store'=>['admin'],
            'tecnicos.edit'=>['admin'],
            'tecnicos.update'=>['admin'],
            'tecnicos.destroy'=>['admin'],
            'formapagos.index'=>['admin'],
            'formapagos.create'=>['admin'],
            'formapagos.store'=>['admin'],
            'formapagos.edit'=>['admin'],
            'formapagos.update'=>['admin'],
            'formapagos.destroy'=>['admin'],
            'tasabcvs.index'=>['admin'],
            'tasabcvs.create'=>['admin'],
            'tasabcvs.store'=>['admin'],
            'tasabcvs.edit'=>['admin'],
            'tasabcvs.update'=>['admin'],
            'tasabcvs.destroy'=>['admin'],
            'localeEmpleados.index'=>['admin'],
            'localeEmpleados.create'=>['admin'],
            'localeEmpleados.store'=>['admin'],
            'localeEmpleados.edit'=>['admin'],
            'localeEmpleados.update'=>['admin'],
            'localeEmpleados.destroy'=>['admin'],
            'productos.index'=>['admin'],
            'productos.create'=>['admin'],
            'productos.store'=>['admin'],
            'productos.edit'=>['admin'],
            'productos.update'=>['admin'],
            'productos.destroy'=>['admin'],
            'ubicaciones.index'=>['admin'],
            'ubicaciones.create'=>['admin'],
            'ubicaciones.store'=>['admin'],
            'ubicaciones.edit'=>['admin'],
            'ubicaciones.update'=>['admin'],
            'ubicaciones.destroy'=>['admin'],
            'clientes.index'=>['admin','vendedor'],
            'clientes.create'=>['admin','vendedor'],
            'clientes.destroy'=>['admin'],
            'clientes.update'=>['admin','vendedor'],
            'clientes.store'=>['admin','vendedor'],
            'clientes.edit'=>['admin','vendedor'],
            'ventas.index'=>['admin','vendedor'],
            'ventas.create'=>['admin','vendedor'],
            'ventas.store'=>['admin','vendedor'],
            'ventas.show'=>['admin','vendedor'],
            'ventas.destroy'=>['admin'],
            'comisiones.index'=>['admin'],
            'comisiones.create'=>['admin'],
            'comisiones.store'=>['admin'],
            'comisiones.edit'=>['admin'],
            'comisiones.update'=>['admin'],
            'comisiones.destroy'=>['admin'],
            'api.ventas.buscar-clientes'=>['admin','vendedor'],
            'api.ventas.crear-cliente'=>['admin','vendedor'],
            'api.ventas.buscar-productos'=>['admin','vendedor'],
            'api.ventas.productos'=>['admin','vendedor'],
            'api.ventas.validar-stock'=>['admin','vendedor'],
            'api.ventas.calcular-totales'=>['admin'],   
            'pagos.index'=>['jefe'],
            'pagos.create'=>['jefe'],
            'pagos.store'=>['jefe'],
           
           


            


            
            
            
            
            
            
            

            


            
            
            
        ];
    
